---
version: '0.2'

ignorePaths: []
dictionaryDefinitions: []
import: []

dictionaries:
  - en_US
  - bash

words:
  - debuggee # the program being debugged

ignoreWords:
  # names
  - georglauterbach
  - Georg
  - Lauterbach

  # proper nouns
  - LLDB
  - rustup
  - shellcheck
  - trixie

  # multiple words written as one
  - cooldown
  - devcontainers
  - libbash
